core/urls.py
from os import name
from django.urls import path,include
from .views import *
app_name="core"
urlpatterns = [

    # path('test/',testview,name='test'),
    path('termsandconditions/',termsAndConditions,name='termsandconditions'),
    
    path ("",index,name='index'),
    path('newsletter/subscribe/',subscribeToNewsLetter,name='newsletter_sub'),
    path('get-intouch/',getintouch,name='getintouch'),
    path ("registation/",signup_page,name='signup'),
    path('registation/complect/',reg_complect,name='reg_complect'),
    
    path ("publications/",publication,name='publications'),
    path ("articles/",articles,name='articles'),
  
    path ("article-and-publication/<slug:slug>/",BlogAndArticleDetails.as_view(),name='blogAndArticle'),
    path ("gallery/",gallaryView,name='gallery'),
    path ("gallery/<slug:curr_semester_slug>/",gallaryView,name='gallery'),

    # news
    
    path('news/',newsListView,name='news'),
    path('news/<slug:slug>/',NewsDetailsView.as_view(),name='news_details'),

    # event 


    path('event/details/<slug:slug>/',EventDetails.as_view(),name='event'),
    path('event/<slug:slug>/',eventView,name='event_list'),


    # comments 

    path('create/comment/<str:commentFor>/<slug:slug>/',createComment,name='createComment'),
    path('add_replay/<int:pk>/',addReplay,name='addReplay'),
    

    # api 
    path('api/gallery/',GalleryListAPIView.as_view(),name='api_gallery'),
    path('api/gallery/<slug:curr_semester_slug>/',GalleryListAPIView.as_view(),name='api_gallery')
    
    
]

robotic_club/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.generic import TemplateView
from core import urls
from django.contrib.auth import views as auth_views #new
import os 

admin.site.site_header = "Admin"
admin.site.site_title = "admin"
admin.site.index_title = "WELCOME TO PORTAL"
urlpatterns=[
    path('admin/login/', auth_views.LoginView.as_view(template_name='admin/register.html'), name='login'), #new
    path('admin/logout/', auth_views.LogoutView.as_view(template_name='admin/logout.html'), name='logout'), #new
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path("select2/", include("django_select2.urls"))
    

]
if os.getenv('MAINTAINS','off') == "on" :
    urlpatterns=[
        *urlpatterns,
        # match any url link that don't start with admin
        re_path(r'^((?!admin).)*$',TemplateView.as_view(template_name="maintains.html"))
    ]
else:
    

    urlpatterns = [
        *urlpatterns,
        # path("m",TemplateView.as_view(template_name="maintains.html")),
        path('',include(urls)),
        path('members/',include('members.urls')),

    ]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms.widgets import TextInput

from .models import( BlogAndArticle, Comments,LastNews,Semester, WhyJoin)
class BlogAndArticleAdminForm(forms.ModelForm):
    # viewcount=forms.IntegerField(disabled=True,required=False,help_text='view count can\'t be alter ')
    class Meta:
        model=BlogAndArticle
        fields='__all__'
    
    def clean(self):
        cleaned_data = super(BlogAndArticleAdminForm,self).clean()

        category=cleaned_data.get("category")
        artical_t=cleaned_data.get('article_type')

        print(category,artical_t)
        if category is not None and category.article_type != artical_t :
            self.add_error('category','This Article Type does not match with category')

        

class LastNewsAdminForm(forms.ModelForm):
    # viewcount=forms.IntegerField(disabled=True,required=False,help_text='view count can\'t be alter ')
    class Meta:
        model=LastNews
        fields='__all__'


class SemesterAdminForm(forms.ModelForm):
    id=forms.IntegerField(widget=forms.HiddenInput,required=False)
    class Meta:
        model=Semester
        exclude=['prioritys_combain',]
    def clean(self):
        
        cleaned_data = super(SemesterAdminForm,self).clean()

        priority=cleaned_data.get("priority")
        semester_year=cleaned_data.get("semester_year")
        id=cleaned_data.get('id')
        if Semester.objects.filter(semester_year=semester_year,priority=priority).exclude(id=id).count()!=0:
            self.add_error('priority',f"not unique for {semester_year}")




class CreateCommentForm(forms.ModelForm):

    class Meta:
        model=Comments
        exclude=['replay']
    

    
class WhyJoinAdminForm(forms.ModelForm):
    reason=forms.CharField(widget=forms.Textarea(),help_text='Max character 500')
    class Meta:
        model=WhyJoin
        fields='__all__'

core/views.py
from datetime import timedelta
from re import A

from django.core.checks import messages
from django.http.response import Http404, HttpResponseBadRequest
from django.shortcuts import redirect, render,get_object_or_404
from django.urls.base import reverse
from core.forms import CreateCommentForm
from core.send_mail import SendMail
from core.serializer import EventSerializer
from members.forms import RegMemberForm
from django.db.models import F,Count
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hitcount.views import HitCountDetailView

from members.models import MemberViews
from .models import (ARTICLE_TYPE, Announcement, Category, ClubEvent, 
                    ClubInfo,BlogAndArticle, Comments, 
                    GetinTouch, Images,
                    LastNews,Affiliates,
                    NewsLetter, Semester, 
                    TermsAndCondition, WhatWedid, 
                    WhyJoin)
from .utils.testingRatelimiter import ratelimit
# from ratelimit.decorators import ratelimit
from .utils.blacklist_ratelimited import blacklist_ratelimited
# import ratelimit

# Create your views here.

class CreateCommentOption:
    EVENTS="EVENTS"
    BLOGS="BLOGS"

def testview(request):
    qs=BlogAndArticle.objects.all()
    return render(request,'core\Latest Blog.html',{'object_list':qs})
    
def termsAndConditions(request):
    object=TermsAndCondition.objects.get()

    return render(request,
        'TermsAndConditions.html',
        {
            'object':object,

        })

@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def createComment(request,commentFor,slug):


    if request.method!='POST':
        return  redirect('core:index')

    obj=None
    if commentFor==CreateCommentOption.EVENTS:
        obj=get_object_or_404(ClubEvent,slug=slug)
    elif commentFor==CreateCommentOption.BLOGS:
        obj=get_object_or_404(BlogAndArticle,slug=slug)
    
    if obj is None:
        return Http404()

    form = CreateCommentForm(request.POST)

    if form.is_valid():
        comment=form.save()
        obj.comments.add(comment)
    
    if 'next' in request.POST:
        return redirect(request.POST.get('next','core:index'))
    else:
        return redirect('core:index')
    
@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def addReplay(request,pk):

    if request.method !='POST':
        return HttpResponseBadRequest()

    obj=get_object_or_404(Comments,pk=pk)

    form= CreateCommentForm(request.POST)
    if form.is_valid():
        new_obj=form.save()
        obj.replay.add(new_obj)
        obj.save()
    return redirect(request.POST.get('next','core:index'))


        


    
    



@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def subscribeToNewsLetter(request):



    if request.method=='POST' and 'next' in request.POST and 'email' in request.POST:

        email=request.POST.get('email',None)

        if email:
            NewsLetter.objects.create(email=email)

        return redirect(request.POST.get('next','core:index'))
    return redirect('core:index')



# @ratelimit(key='user_or_ip', rate='50/m', block=False)
# @blacklist_ratelimited(timedelta(minutes=30))       
def getintouch(request):

    if request.method == 'POST' and 'fullname' in  request.POST and 'email' in request.POST and 'discription' in request.POST:
        try:
            GetinTouch.objects.create(
                fullname=request.POST.get('fullname',''),
                email=request.POST.get('email',''),
                discription=request.POST.get('discription',''),
            )
          


        except:
            pass 

    return redirect('core:index')






def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

@cache_page(60 * 2)
def index(request):
    
    blogsAndarticles=BlogAndArticle.objects.filter(
            article_type=ARTICLE_TYPE.get_types().get('article')
        ).order_by('-created')[:5]

    # lastnews=LastNews.objects.all().order_by('-created')[:5]
    lastnews=Announcement.objects.all()[:5]
    affiliates=Affiliates.objects.all()
    whyjoins=WhyJoin.objects.all()

    whatwedid=WhatWedid.objects.all()

    events=ClubEvent.objects.values('id','slug',
        'title','picture',
        'created').order_by('-created')[:5]

    


    context={
       
        'blogsAndarticles':blogsAndarticles,
        'lastnews':lastnews,
        'affiliates':affiliates,
        'whyjoins':whyjoins,
        'whatwedid':whatwedid,
        'events':events,
        
    }
    
    return render(request,template_name='./core/index.html',context=context)

@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def signup_page(request):
    form=RegMemberForm()

    club=ClubInfo.objects.get()
    if request.method=='POST' and club.registation_form_open:
        form=RegMemberForm(request.POST,request.FILES)
        if(form.is_valid()):
            obj=form.save()
            SendMail().sendorBrodcast_WithTemplate(request,obj.email,f'[{club.name}]Registration has complect','reg_complect_email.html',{'username':obj.name,'clubname':club.name})

            return redirect('core:reg_complect')
            
        
    context={
        'form':form,

    }
    
    return render(request,template_name='./core/signup.html',context=context)

def reg_complect(request):
    return render(request,'core/reg_complect.html')

def articles_and_publication(request,article_t):
    page = request.GET.get('page', 1)
    category=request.GET.get('catagory')
    title=request.GET.get('title')
    object_list=BlogAndArticle.objects.filter(article_type=article_t).order_by('-created')
    if category is not None:
        object_list=BlogAndArticle.objects.filter(category__name__startswith=category)
    if title is not None:
        object_list=BlogAndArticle.objects.filter(title__icontains=title)
    popular_obj=object_list.order_by('-hit_count_generic__hits').first()
    # one to may relation
    categorys=Category.objects.filter(article_type=article_t).annotate(num_of_blogandarticle=Count('blogandarticle'))
    paginator = Paginator(object_list, 12)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)

    ctx={
        'object_list':object_list,
        'popular_obj':popular_obj,
        'categorys':categorys
    }
    return ctx
    # print(popular_obj)
    # return render(request,template_name='core/article_list.html',context=ctx)

def publication(request):
    article_t=ARTICLE_TYPE.get_types().get('publication')
    ctx=articles_and_publication(request,article_t)
    ctx={
        **ctx,
        'banner_title':'Publication'
    }
    return render(request,template_name='core/article_list.html',context=ctx)

def articles(request):
    article_t=ARTICLE_TYPE.get_types().get('article')
    ctx=articles_and_publication(request,article_t)
    ctx={
        **ctx,
        'banner_title':'Article'
    }
    return render(request,template_name='core/article_list.html',context=ctx)

class BlogAndArticleDetails(HitCountDetailView):
    model = BlogAndArticle
    context_object_name = "object"
    # template_name = "./core/activityDtails.html"
    template_name = "./core/blog-details.html"
    count_hit = True

    def get_object(self):
        slug = self.kwargs.get("slug")
        
        return get_object_or_404(
            BlogAndArticle,
            slug=slug,
        )
    def get_context_data(self, **kwargs):
        context = super(BlogAndArticleDetails, self).get_context_data(**kwargs)
        obj=self.get_object()

        createComment_url=reverse('core:createComment',kwargs={'commentFor':CreateCommentOption.BLOGS,'slug':self.kwargs.get("slug")})
        # categorys=Category.objects.filter(article_type=obj.article_type).annotate(num_of_blogandarticle=Count('blogandarticle'))
        
        similar_object=BlogAndArticle.objects.filter(article_type=obj.article_type,category= obj.category).exclude(id=obj.id)[:3]
        
        banner_title="Article/Details"
        url_active='article'

        for t in ARTICLE_TYPE.get_types():
            if ARTICLE_TYPE.get_types()[t]==obj.article_type:
                banner_title=t.capitalize()+"/Details"
                url_active=t
                break
        

        
        context.update({
        # 'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:3],
        'createComment_url':createComment_url,
        # 'categorys':categorys,
        'similar_object':similar_object,
        'banner_title':banner_title,
        'url_active':url_active
        })
        return context



def gallaryView(request,curr_semester_slug=None):
    imgs=Images.objects.all()
    semesters=Semester.objects.all()
    
    if curr_semester_slug is None:
        try:
            curr_semester_slug=semesters.first().slug
        except :
            curr_semester_slug=None
    ctx={
        'imagesList':imgs,
        'semesters':semesters,
        'curr_semester_slug':curr_semester_slug,
    }
    return render(request,template_name='./core/gallery.html',context=ctx)

# https://www.figma.com/file/8JmADeuWZkLSmlF2L2vG4h/Betel-Leaf-RACEWU?node-id=105%3A19

class EventDetails(HitCountDetailView):

    model = ClubEvent
    context_object_name = "object"
    template_name = "./core/activityDtails.html"
    count_hit = True

    def get_object(self):
        
        slug = self.kwargs.get("slug")
        
        return get_object_or_404(
            ClubEvent,
       
            slug=slug
        )

core/templates/core/article_list.html
{%extends 'core/index.html'%}
{%load static%}

<!-- PAGE TITLE HERE -->


{%block metatag%}
<!-- article list -->
<title>Articles - {{clubinfo.sort_name}}</title>
<meta name="title" content="Articles - {{clubinfo.sort_name}}">
<meta name="description" content="Find the out our last articles. {{clubinfo.meta_description}}">



<meta property="og:image" content="{% if clubinfo.landing_picture %}{{clubinfo.landing_picture.url}}{%endif%}">
<meta property="og:title" content="Articles- {{clubinfo.sort_name}}">
<meta property="og:description" content="Find the out our last articles.">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Articles- {{clubinfo.sort_name}}">
<meta name="twitter:description" content="Find the out our last articles.">
<meta name="twitter:image" content="{% if clubinfo.landing_picture %}{{clubinfo.landing_picture.url}}{%endif%}">
{%endblock%}


{%block body%}




<!-- MOBILE SPECIFIC -->
<meta name="viewport" content="width=device-width, initial-scale=1" />


<!-- STYLESHEETS -->
<link rel="stylesheet" type="text/css" href="/static/css/plugins.css" />
<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
<link rel="stylesheet" type="text/css" href="/static/css/templete.css" />
<link class="skin" rel="stylesheet" type="text/css" href="/static/css/skin/skin-1.css" />

{{clubinfo.get_font_links}}

{{clubinfo.loadtheam|safe}}
<body id="bg">






  <!-- inner page banner -->
  <!-- <div class="blog_page dlab-bnr-inr dlab-bnr-inr-sm overlay-black-middle"
    style='background-image: url({% if clubinfo.landing_picture %}{{clubinfo.landing_picture.url}}{%else%} {%static "img/2_35__1.png"%} {%endif%})'>
    <div class="container">
      <div class="dlab-bnr-inr-entry">
        <h1 class="text-white">Blog & Article</h1>
      </div>
    </div>
  </div> -->
  <!-- inner page banner END -->



 
  {%include 'lending_pic.html'%}


  <!-- Content -->
  <div class="page-content bg-white">

    <!-- inner page banner END -->
    <div class="section-full content-inner">
      <div class="container">

        
          
  
        <!-- Left part start -->
        <div class="row" style="overflow: hidden;">
          <div class="col-lg-8 col-xl-8 p-b30 p-t30 p-r20">
            <h1 class="d-none" style=" border-bottom: 0.5px solid #353535; padding-bottom: 3px;"> Articles </h1>
            <div class="row">
              {% for object in object_list %}
              <div class="col-lg-4 col-md-6 col-sm-6 m-b30" >
                <div class="listing-bx"  data-aos="fade-up" >
                  <div class="listing-media">
                    <img loading="lazy" src="{%if object.picture%}{{object.picture.url}} {%endif%} " alt="" />
                  </div>
                  <div class="d-flex  flex-column mt-2 px-2" style="justify-content: space-around;">
                    <a class="h6 text-dark font-weight-600" href="{%url 'core:blogAndArticle' slug=object.slug%}">
                      {{object.title}}
                    </a>
                    <p>{{object.created}} </p>

                  </div>
                </div>
              </div>
              
              {%empty%}
            <h5>
                No Data Found.
            </h5>

            {% endfor %}
              
            </div>
            

            {% if object_list.has_other_pages %}
            <nav aria-label="Page navigation ">
            <ul class="pagination ">
                {% if object_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}" tabindex="-1">&laquo;</a></li>
                {% else %}
                <li class="page-item disabled"><span class="page-link" >&laquo;</span></li>
                {% endif %}
                {% for i in object_list.paginator.page_range %}
                {% if object_list.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only"></span> </span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if object_list.has_next %}
                <li  class="page-item"><a class="page-link"href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link">Next</a></li>
                {% endif %}
            </ul>
            </nav>
            {% endif %}


          </div>
          <!-- Left part END -->
          <!-- Side bar start -->
          <div class="col-lg-4 col-xl-4 sticky-top p-t20 p-l30">
            <aside class="side-bar blog-sidebar">
              <div class="widget">
                <h4 class="widget-title">Search</h4>
                <div class="search-bx">
                  <form role="search" method="get" >
                    <div class="input-group">
                     
                      <input name="title" type="text"  class="form-control" placeholder="Search your keyword..."
                        style="border-radius: 88px;" />
                      <i class="fa fa-search icon"></i>
                    </div>
                  </form>
                  
                </div>
              </div>

              <div class="widget widget_tag">
                <h4 class="widget-title">Categories</h4>
                <ul class="m-b0">
                  {%for category in categorys%}
                  <li>
                    <a href="./?catagory={{category.name}}">{{category.name}}</a> ({{category.num_of_blogandarticle}})
                  </li>
                  {%endfor%}
                </ul>
              </div>

              {%include 'core/components/newsletter.html'%}
             
              {%include 'core/components/follow-socal-link.html'%}
              

              

              <div>
                {%include 'core/components/top_post.html'%}
              </div>

            </aside>
          </div>
          <!-- Side bar END -->
        </div>
      </div>
    </div>
  </div>


  </div>

  <br>

      <!-- JAVASCRIPT FILES ========================================= -->
      <script src="/static/js/jquery.min.js"></script>
      
      <!-- FORM JS -->
      <script src="/static/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script>
      
      <!-- OWL SLIDER -->
      <script src="/static/js/custom.js"></script>
      
  {%endblock%}

core/templates/core/blog-details.html
{%extends 'core/index.html'%}
{%load static%}
{% load hitcount_tags %}
{%block metatag%}


<!-- blog-details.html -->
<meta name="title" content="{{object.title}} - {{clubinfo.sort_name}}">
<meta name="description" content="{{object.shortDescription}}">



<meta property="og:image" content="{%if object.picture %}{{object.picture.url}}{%endif %}">
<meta property="og:title" content="{{object.title}} - {{clubinfo.sort_name}}">
<meta property="og:description" content="{{object.shortDescription}}">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{object.title}} - {{clubinfo.sort_name}}">
<meta name="twitter:description" content="{{object.shortDescription}}">
<meta name="twitter:image" content="{%if object.picture %}{{object.picture.url}}{%endif %}">


<title>{{object.title}} - {{clubinfo.sort_name}} </title>

{%endblock%}

{%block body%}


<!-- STYLESHEETS -->
<link rel="stylesheet" type="text/css" href="/static/css/plugins.css" />
<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
<link rel="stylesheet" type="text/css" href="/static/css/templete.css" />
<link class="skin" rel="stylesheet" type="text/css" href="/static/css/skin/skin-1.css" />
{{clubinfo.get_font_links}}

{{clubinfo.loadtheam|safe}}

<style>

li.post-author {
    border-left: 2px solid var(--secondary);
    padding-left: 5px;

}

</style>


{%include 'lending_pic.html'%}

<div id="loading-area"></div>
<div class="page-wraper">
  <!-- header -->
  <!-- Content -->
  <div class="page-content bg-white">
    <!-- inner page banner -->

    <!-- inner page banner END -->
    <div class="section-full content-inner">
      <div class="container">
        <!-- Left part start -->
        <div class="row">
          <div class=" p-b30 p-t20 p-r25 ">
            <!-- blog start -->
            <div class="dlab-post-title px-2 px-lg-5">
              <h2 class="post-title m-t0">
                <a href="">{{object.title}}</a>
              </h2>
            </div>

            <div class="blog-post blog-single">
              <div class="dlab-post-meta m-b20 px-2 px-lg-5">
                
                <ul class="d-flex align-items-center blogpost">
                  <li class="post-author">
                    <span style="font-size: small; color: black;">
                      Views
                    </span>
                    <br>
                    <span class="" style="font-size: smaller;">
                      {% get_hit_count for object %}
                    </span>
                  </li>
                  {%if object.category is not None%}
                  <li class="post-author">
                    <span style="font-size: small;color: black;">
                      Category
                    </span>
                    <span class="" style="font-size: smaller;">
                      <br>
                      {{object.category.name}}
                    </span>

                  </li>
                  {%endif%}
                  <li class="post-author">


                    <span style="font-size: small;color: black;">
                      Date
                    </span>
                    <br>
                    <span class="" style="font-size: smaller;">
                      {{object.created}}
                    </span>
                  </li>
                  <li class="post-author">
                    
                      
                      <span style="font-size: small;color: black;">
                        Comments
                      </span>
                      <br>
                      <span class="" style="font-size: smaller;">
                        

                        {%with comment_num=object.comments.all.count%}
                        {%if ocomment_num > 1 %}
                        {{comment_num}} COMMENTS
                        {%else%}
                        {{comment_num}} COMMENT
                        {%endif%}
                        {%endwith%}

                      </span>
                  </li>
                </ul>
              </div>

              <div class="dlab-post-text">
                <div class="dlab-post-media m-b50 d-flex justify-content-center">

                  <img src="{%if object.picture%}{{object.picture.url}}{%endif%}" style="width: 100%;  
                  aspect-ratio: 2.35/1;
                  object-fit: contain;
                  object-position: center;
                  " alt="img" />

                </div>

                <div class="px-2 px-md-5" style=" word-break: break-word;">
                  {{object.content|safe}}
                </div>
              </div>

              <div class="clearfix">
                <div class="float-right text-right">
                  <ul class="list-inline m-t20 m-b0">
                    <li>Share:</li>
                    <li>
                      
                      <a href="https://www.facebook.com/sharer/?u={{request.build_absolute_uri}}" class="site-button-link gray-light fa fa-facebook-f"></a>
                    </li>
                    <li>
                      <a href="https://twitter.com/share?url={{request.build_absolute_uri}}&text={{object.title}}" class="site-button-link gray-light fa fa-twitter"></a>
                    </li>
                    
                    <li>
                      <a href="https://www.linkedin.com/shareArticle?url={{request.build_absolute_uri}}" class="site-button-link gray-light fa fa-linkedin"></a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="dlab-divider bg-gray-dark"></div>
              <h4>You May also Like</h4>
              <div class="row">

                {%for obj in similar_object%}
                <div class="col-xl-4 col-lg-6 col-md-6 col-xs-12">
                  <div class="blog-post blog-lg list-blog-bx">
                    <div class="dlab-post-media dlab-img-effect zoom-slow">
                      <a href="javascript:void(0);"><img src="{%if obj.picture%}{{obj.picture.url}}{%endif%}" alt="img"  style="width: 100%;"/></a>
                    </div>
                    <div class="dlab-post-info">
                      <div class="dlab-post-title">
                        <h6 class="post-title">
                          <a href="{{obj.get_absolute_url}}">{{obj.title}}</a>
                        </h6>
                      </div>
                      <div class="dlab-post-text mb-0">
                        <p class="m-b0">{{obj.created}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                {%endfor%}
                
              </div>
            </div>
            {%include 'core/components/comments.html'%}
            <!-- blog END -->
          </div>
          <!-- Left part END -->
          <!-- Side bar start -->
          <div class=" sticky-top p-t20 p-l30 d-none">
            <aside class="side-bar blog-sidebar">
              <div class="widget">
                <h4 class="widget-title">Search</h4>
                <div class="search-bx">
                  <form role="search" method="get" action="/blogsAndArticles/">
                    <div class="input-group">
                      <input name="title" type="text" class="form-control" placeholder="Search your keyword..." style="border-radius: 88px;" />
                      <i class="fa fa-search icon"></i>
                    </div>
                  </form>
                </div>
              </div>

              <div class="widget widget_tag">
                <h4 class="widget-title">Categories</h4>
                <ul class="m-b0">
                  {%for category in categorys%}
                  <li>
                    <a href="/blogsAndArticles/?catagory={{category.name}}">{{category.name}}</a> ({{category.num_of_blogandarticle}})
                  </li>
                  {%endfor%}
                </ul>
              </div>
            </aside>
          </div>
          <!-- Side bar END -->
        </div>
      </div>
    </div>
  </div>
  <!-- Content END-->
</div>

     <!-- JAVASCRIPT FILES ========================================= -->
     <script src="/static/js/jquery.min.js"></script>
      
     <!-- FORM JS -->
     <script src="/static/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script>
     
     <!-- OWL SLIDER -->
     <script src="/static/js/custom.js"></script>
     

{%endblock body%}

core/templates/core/reg_complect.html
{% extends 'core/index.html' %}
{%load static %}




{%block body%}


<section class="container fs-1" style="margin-top: 48px; min-height: 20vh;">
    <div class="pageContex text-center">Your registation Has complected</div>
</section>


{%endblock%}