core/urls.py
from os import name
from django.urls import path,include
from .views import *
app_name="core"
urlpatterns = [

    # path('test/',testview,name='test'),
    path('termsandconditions/',termsAndConditions,name='termsandconditions'),
    
    path ("",index,name='index'),
    path('newsletter/subscribe/',subscribeToNewsLetter,name='newsletter_sub'),
    path('get-intouch/',getintouch,name='getintouch'),
    path ("registation/",signup_page,name='signup'),
    path('registation/complect/',reg_complect,name='reg_complect'),
    
    path ("publications/",publication,name='publications'),
    path ("articles/",articles,name='articles'),
  
    path ("article-and-publication/<slug:slug>/",BlogAndArticleDetails.as_view(),name='blogAndArticle'),
    path ("gallery/",gallaryView,name='gallery'),
    path ("gallery/<slug:curr_semester_slug>/",gallaryView,name='gallery'),

    # news
    
    path('news/',newsListView,name='news'),
    path('news/<slug:slug>/',NewsDetailsView.as_view(),name='news_details'),

    # event 


    path('event/details/<slug:slug>/',EventDetails.as_view(),name='event'),
    path('event/<slug:slug>/',eventView,name='event_list'),


    # comments 

    path('create/comment/<str:commentFor>/<slug:slug>/',createComment,name='createComment'),
    path('add_replay/<int:pk>/',addReplay,name='addReplay'),
    

    # api 
    path('api/gallery/',GalleryListAPIView.as_view(),name='api_gallery'),
    path('api/gallery/<slug:curr_semester_slug>/',GalleryListAPIView.as_view(),name='api_gallery')
    
    
]

members/urls.py
from django.urls import path

from .views import *

app_name='members'
urlpatterns=[


    path('alumni/',alumni_view,name='alumni_view'),
    path('<slug:slug>/',simpleMembersView,name='members_list'),
    path('<slug:slug>/<slug:clubyear_slug>/',simpleMembersView,name='members_list'),

]

robotic_club/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.generic import TemplateView
from core import urls
from django.contrib.auth import views as auth_views #new
import os 

admin.site.site_header = "Admin"
admin.site.site_title = "admin"
admin.site.index_title = "WELCOME TO PORTAL"
urlpatterns=[
    path('admin/login/', auth_views.LoginView.as_view(template_name='admin/register.html'), name='login'), #new
    path('admin/logout/', auth_views.LogoutView.as_view(template_name='admin/logout.html'), name='logout'), #new
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path("select2/", include("django_select2.urls"))
    

]
if os.getenv('MAINTAINS','off') == "on" :
    urlpatterns=[
        *urlpatterns,
        # match any url link that don't start with admin
        re_path(r'^((?!admin).)*$',TemplateView.as_view(template_name="maintains.html"))
    ]
else:
    

    urlpatterns = [
        *urlpatterns,
        # path("m",TemplateView.as_view(template_name="maintains.html")),
        path('',include(urls)),
        path('members/',include('members.urls')),

    ]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms.widgets import TextInput

from .models import( BlogAndArticle, Comments,LastNews,Semester, WhyJoin)
class BlogAndArticleAdminForm(forms.ModelForm):
    # viewcount=forms.IntegerField(disabled=True,required=False,help_text='view count can\'t be alter ')
    class Meta:
        model=BlogAndArticle
        fields='__all__'
    
    def clean(self):
        cleaned_data = super(BlogAndArticleAdminForm,self).clean()

        category=cleaned_data.get("category")
        artical_t=cleaned_data.get('article_type')

        print(category,artical_t)
        if category is not None and category.article_type != artical_t :
            self.add_error('category','This Article Type does not match with category')

        

class LastNewsAdminForm(forms.ModelForm):
    # viewcount=forms.IntegerField(disabled=True,required=False,help_text='view count can\'t be alter ')
    class Meta:
        model=LastNews
        fields='__all__'


class SemesterAdminForm(forms.ModelForm):
    id=forms.IntegerField(widget=forms.HiddenInput,required=False)
    class Meta:
        model=Semester
        exclude=['prioritys_combain',]
    def clean(self):
        
        cleaned_data = super(SemesterAdminForm,self).clean()

        priority=cleaned_data.get("priority")
        semester_year=cleaned_data.get("semester_year")
        id=cleaned_data.get('id')
        if Semester.objects.filter(semester_year=semester_year,priority=priority).exclude(id=id).count()!=0:
            self.add_error('priority',f"not unique for {semester_year}")




class CreateCommentForm(forms.ModelForm):

    class Meta:
        model=Comments
        exclude=['replay']
    

    
class WhyJoinAdminForm(forms.ModelForm):
    reason=forms.CharField(widget=forms.Textarea(),help_text='Max character 500')
    class Meta:
        model=WhyJoin
        fields='__all__'

core/views.py
from datetime import timedelta
from re import A

from django.core.checks import messages
from django.http.response import Http404, HttpResponseBadRequest
from django.shortcuts import redirect, render,get_object_or_404
from django.urls.base import reverse
from core.forms import CreateCommentForm
from core.send_mail import SendMail
from core.serializer import EventSerializer
from members.forms import RegMemberForm
from django.db.models import F,Count
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hitcount.views import HitCountDetailView

from members.models import MemberViews
from .models import (ARTICLE_TYPE, Announcement, Category, ClubEvent, 
                    ClubInfo,BlogAndArticle, Comments, 
                    GetinTouch, Images,
                    LastNews,Affiliates,
                    NewsLetter, Semester, 
                    TermsAndCondition, WhatWedid, 
                    WhyJoin)
from .utils.testingRatelimiter import ratelimit
# from ratelimit.decorators import ratelimit
from .utils.blacklist_ratelimited import blacklist_ratelimited
# import ratelimit

# Create your views here.

class CreateCommentOption:
    EVENTS="EVENTS"
    BLOGS="BLOGS"

def testview(request):
    qs=BlogAndArticle.objects.all()
    return render(request,'core\Latest Blog.html',{'object_list':qs})
    
def termsAndConditions(request):
    object=TermsAndCondition.objects.get()

    return render(request,
        'TermsAndConditions.html',
        {
            'object':object,

        })

@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def createComment(request,commentFor,slug):


    if request.method!='POST':
        return  redirect('core:index')

    obj=None
    if commentFor==CreateCommentOption.EVENTS:
        obj=get_object_or_404(ClubEvent,slug=slug)
    elif commentFor==CreateCommentOption.BLOGS:
        obj=get_object_or_404(BlogAndArticle,slug=slug)
    
    if obj is None:
        return Http404()

    form = CreateCommentForm(request.POST)

    if form.is_valid():
        comment=form.save()
        obj.comments.add(comment)
    
    if 'next' in request.POST:
        return redirect(request.POST.get('next','core:index'))
    else:
        return redirect('core:index')
    
@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def addReplay(request,pk):

    if request.method !='POST':
        return HttpResponseBadRequest()

    obj=get_object_or_404(Comments,pk=pk)

    form= CreateCommentForm(request.POST)
    if form.is_valid():
        new_obj=form.save()
        obj.replay.add(new_obj)
        obj.save()
    return redirect(request.POST.get('next','core:index'))


        


    
    



@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def subscribeToNewsLetter(request):



    if request.method=='POST' and 'next' in request.POST and 'email' in request.POST:

        email=request.POST.get('email',None)

        if email:
            NewsLetter.objects.create(email=email)

        return redirect(request.POST.get('next','core:index'))
    return redirect('core:index')



# @ratelimit(key='user_or_ip', rate='50/m', block=False)
# @blacklist_ratelimited(timedelta(minutes=30))       
def getintouch(request):

    if request.method == 'POST' and 'fullname' in  request.POST and 'email' in request.POST and 'discription' in request.POST:
        try:
            GetinTouch.objects.create(
                fullname=request.POST.get('fullname',''),
                email=request.POST.get('email',''),
                discription=request.POST.get('discription',''),
            )
          


        except:
            pass 

    return redirect('core:index')






def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

@cache_page(60 * 2)
def index(request):
    
    blogsAndarticles=BlogAndArticle.objects.filter(
            article_type=ARTICLE_TYPE.get_types().get('article')
        ).order_by('-created')[:5]

    # lastnews=LastNews.objects.all().order_by('-created')[:5]
    lastnews=Announcement.objects.all()[:5]
    affiliates=Affiliates.objects.all()
    whyjoins=WhyJoin.objects.all()

    whatwedid=WhatWedid.objects.all()

    events=ClubEvent.objects.values('id','slug',
        'title','picture',
        'created').order_by('-created')[:5]

    


    context={
       
        'blogsAndarticles':blogsAndarticles,
        'lastnews':lastnews,
        'affiliates':affiliates,
        'whyjoins':whyjoins,
        'whatwedid':whatwedid,
        'events':events,
        
    }
    
    return render(request,template_name='./core/index.html',context=context)

@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def signup_page(request):
    form=RegMemberForm()

    club=ClubInfo.objects.get()
    if request.method=='POST' and club.registation_form_open:
        form=RegMemberForm(request.POST,request.FILES)
        if(form.is_valid()):
            obj=form.save()
            SendMail().sendorBrodcast_WithTemplate(request,obj.email,f'[{club.name}]Registration has complect','reg_complect_email.html',{'username':obj.name,'clubname':club.name})

            return redirect('core:reg_complect')
            
        
    context={
        'form':form,

    }
    
    return render(request,template_name='./core/signup.html',context=context)

def reg_complect(request):
    return render(request,'core/reg_complect.html')

def articles_and_publication(request,article_t):
    page = request.GET.get('page', 1)
    category=request.GET.get('catagory')
    title=request.GET.get('title')
    object_list=BlogAndArticle.objects.filter(article_type=article_t).order_by('-created')
    if category is not None:
        object_list=BlogAndArticle.objects.filter(category__name__startswith=category)
    if title is not None:
        object_list=BlogAndArticle.objects.filter(title__icontains=title)
    popular_obj=object_list.order_by('-hit_count_generic__hits').first()
    # one to may relation
    categorys=Category.objects.filter(article_type=article_t).annotate(num_of_blogandarticle=Count('blogandarticle'))
    paginator = Paginator(object_list, 12)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)

    ctx={
        'object_list':object_list,
        'popular_obj':popular_obj,
        'categorys':categorys
    }
    return ctx
    # print(popular_obj)
    # return render(request,template_name='core/article_list.html',context=ctx)

def publication(request):
    article_t=ARTICLE_TYPE.get_types().get('publication')
    ctx=articles_and_publication(request,article_t)
    ctx={
        **ctx,
        'banner_title':'Publication'
    }
    return render(request,template_name='core/article_list.html',context=ctx)

def articles(request):
    article_t=ARTICLE_TYPE.get_types().get('article')
    ctx=articles_and_publication(request,article_t)
    ctx={
        **ctx,
        'banner_title':'Article'
    }
    return render(request,template_name='core/article_list.html',context=ctx)

class BlogAndArticleDetails(HitCountDetailView):
    model = BlogAndArticle
    context_object_name = "object"
    # template_name = "./core/activityDtails.html"
    template_name = "./core/blog-details.html"
    count_hit = True

    def get_object(self):
        slug = self.kwargs.get("slug")
        
        return get_object_or_404(
            BlogAndArticle,
            slug=slug,
        )
    def get_context_data(self, **kwargs):
        context = super(BlogAndArticleDetails, self).get_context_data(**kwargs)
        obj=self.get_object()

        createComment_url=reverse('core:createComment',kwargs={'commentFor':CreateCommentOption.BLOGS,'slug':self.kwargs.get("slug")})
        # categorys=Category.objects.filter(article_type=obj.article_type).annotate(num_of_blogandarticle=Count('blogandarticle'))
        
        similar_object=BlogAndArticle.objects.filter(article_type=obj.article_type,category= obj.category).exclude(id=obj.id)[:3]
        
        banner_title="Article/Details"
        url_active='article'

        for t in ARTICLE_TYPE.get_types():
            if ARTICLE_TYPE.get_types()[t]==obj.article_type:
                banner_title=t.capitalize()+"/Details"
                url_active=t
                break
        

        
        context.update({
        # 'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:3],
        'createComment_url':createComment_url,
        # 'categorys':categorys,
        'similar_object':similar_object,
        'banner_title':banner_title,
        'url_active':url_active
        })
        return context



def gallaryView(request,curr_semester_slug=None):
    imgs=Images.objects.all()
    semesters=Semester.objects.all()
    
    if curr_semester_slug is None:
        try:
            curr_semester_slug=semesters.first().slug
        except :
            curr_semester_slug=None
    ctx={
        'imagesList':imgs,
        'semesters':semesters,
        'curr_semester_slug':curr_semester_slug,
    }
    return render(request,template_name='./core/gallery.html',context=ctx)

# https://www.figma.com/file/8JmADeuWZkLSmlF2L2vG4h/Betel-Leaf-RACEWU?node-id=105%3A19

class EventDetails(HitCountDetailView):

    model = ClubEvent
    context_object_name = "object"
    template_name = "./core/activityDtails.html"
    count_hit = True

    def get_object(self):
        
        slug = self.kwargs.get("slug")
        
        return get_object_or_404(
            ClubEvent,
       
            slug=slug
        )

core/templates/intropic.html
{%load static%}

<style>
    .intro-pics {

        /* margin-top: 2%; */

        background: url('{% if clubinfo.landing_picture %}{{clubinfo.landing_picture.url}}{%else%} {%static "img/2_35__1.png"%} {%endif%}  ');
        /* width: 101%; */
        height: 65vh;
        /* aspect-ratio: 2.35/1; */


        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;




    }

    @media only screen and (max-width: 990px) {
        .intro-pics {
            object-fit: contain;
            height: 30vh;

            margin-top: 0;

        }
    }
    /*Big smartphones [426px -> 600px]*/
    @media only screen and (max-width: 600px) {

        .intro-pics {
            object-fit: contain;
            height: 15vh;
            margin-top: 0;

        }

    }
</style>


<div class="intro-pics " >

</div>

core/templates/lending_pic.html
{%load static%}

<style>
    .intro-pics {

        /* margin-top: 2%; */

        background: url('{% if clubinfo.landing_picture %}{{clubinfo.landing_picture.url}}{%else%} {%static "img/2_35__1.png"%} {%endif%}  ');
        /* width: 101%; */
        height: 30vh;
        /* aspect-ratio: 2.35/1; */


        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        z-index: -1;
        position: relative;




    }

    .banner_title {
        position: relative;
        top: 50%;
        left: 5%;
        font-size: 3rem;
        font-weight: bolder;
        
        color: white;
        text-shadow: -1px 1px 2px black;
    }

    @media only screen and (max-width: 992px) {
        .intro-pics {
            object-fit: contain;
            height: 30vh;

            margin-top: 0;

        }

        .banner_title {
            font-size: 2.2rem;
            
        }

    }

    /*Big smartphones [426px -> 600px]*/
    @media only screen and (max-width: 576px) {

        .intro-pics {
            object-fit: contain;
            height: 15vh;
            margin-top: 0;

        }

        .banner_title {
            top: 30%;
            font-size: 1.8rem;
        }

    }

    @media only screen and (max-width: 320px) {

        .banner_title {
 
            font-size: 1.5rem;
        }
    }

    .catagory_btn{
        /* background-color: var(--secondary); */
        border-radius: 35px;
        box-shadow: -1px 1px 4px 0px #00000079;
        text-shadow: -1px 1px 4px 0px #00000079;
        border: 2px solid white;
        min-height: 38px;
        width: 150px;
    }
    .catagory_btn:active{
        /* background-color: var(--secondary_liter); */
        box-shadow: -1px 1px 4px -1px #00000079;
    }
    .catagories{
        position: relative;
    top: 60%;
    }
</style>


<div class="intro-pics ">

    {%if banner_title%}
    <div class="" style="background: black;height: 100%;position: absolute;top: 0;left: 0;width: 100%;opacity: 0.5; "></div>
    <span class="banner_title container">{{banner_title}}</span>
    {%endif%}

</div>

core/templates/navbar.html
{%load static%}
<style>
    .navbar {
        width: 100%;
        background-color: white;
        box-shadow: 0 1px 5px rgba(255, 48, 11, 0.438);
        z-index: 10000;
    }

    .navbar-brand {

        width: 85px;

    }

    .navbar-brand img {
        width: 100%;
    }



    .navbar a {

        text-decoration: none !important;


    }

    .navbar-active {
        color: var(--primary) !important;
    }

    .navbar-btn a {
        color: var(--primary) !important;
        font-weight: 600 !important;


    }

    .navbar .hamburger-lines {
        display: block;
        height: 26px;
        width: 32px;
        /* position: absolute; */
        /* top: 17px; */
        /* right: 20px; */
        z-index: 2;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .hamburger-lines .line {
        display: block;
        height: 4px;
        width: 100%;
        border-radius: 10px;
        background: #0e24318c;;
    }


    .hamburger-lines .line1 {
        transform-origin: 0% 0%;
        transition: transform 0.4s ease-in-out;
    }

    .hamburger-lines .line2 {
        transition: transform 0.2s ease-in-out;
    }

    .hamburger-lines .line3 {
        transform-origin: 0% 100%;
        transition: transform 0.4s ease-in-out;
    }



    .line1-active {
        transform: rotate(45deg);
    }

    .line2-active {
        transform: scaleY(0);
    }

    .line3-active {
        transform: rotate(-45deg);
    }

    .navbar-hamburger {
        display: none;
    }


    .navbar .navbar-items {

        display: flex;
        transform: translateX(-4%);
    }

    .navbar-item {
        position: relative;
        margin-left: 10px;
        padding: 10px;
        color: var(--secondary) ;

    }

    .navbar-item:hover {
        color: var(--primary) !important;
    }

    .navbar-item a {
        color: inherit;
    }

    .navbar-item a:hover {
        color: inherit;
    }

    .navbar-dropdown {
        color: inherit;
        cursor: pointer;
        pointer-events: none;
        
    }

    .navbar-dropdown:after {
        content: "";
        position: absolute;
        top: 18px;
        right: -5px;
        /* Example: right:10px; */
        display: inline-block;
        border-right: 4px solid transparent;
        border-top: 4px solid var(--secondary);
        border-left: 4px solid transparent;
    }

    .navbar-dropdown-menu {
        position: absolute;
        max-height: 200px;
        left: 0%;
        z-index: 100;

        overflow: hidden;
        overflow-y: scroll;

        background-color: var(--secondary);
        box-shadow: -1px 1px 10px -1px rgba(0, 0, 0, 0.418);
        border-radius: 10px;

        opacity: 0;
        transform: scale(0);
        transition: all 0.5s ease-in-out;
        transform-origin: top;
        
    }

    .navbar-dropdown-menu::-webkit-scrollbar{
        width: 1px;
    }
    


    .navbar-item:hover .navbar-dropdown-menu {
        /* display:block; */
        opacity: 1;
        transform: scale(1);
        left: 50%;

        transform: translateX(-50%);
    }
   
    .dropdown-item {
        color: var(--text_in_secondary) !important;
        font-size: 1rem !important;
    }

    .dropdown-item:hover {
        background-color: var(--secondary_liter) !important;
        color: var(--text_in_secondary) !important;

    }

    .dropdown-item:focus, .dropdown-item:hover{

color: var(--text_in_secondary) !important;
background-color: var(--secondary_liter) !important;
}

    .bg-cover {
        left: 0;
        width: 100%;
            height: 200vh;
            background: #000000ad;
         
            padding-bottom: 100%;
            position: absolute;
            top: 5.1em;
            z-index: 1050;

        transform:scale(0);
        opacity: 0;
        transform-origin: top;
        transition: opacity 0.8s ease-in-out;
       
        

    }

    @media only screen and (max-width: 992px) {
        

        .navbar-brand {

            width: 65px;

        }


        .navbar .navbar-items {


            position: absolute;
            right: -2%;
            top: 100%;
            width: 60%;
            border-radius: 2px;
            /* overflow: hidden; */
            flex-direction: column;
            padding-bottom: 100%;
            background-color: rgb(255, 255, 255);
            box-shadow: -1px 1px 5px -1px black;
            /* box-shadow: -262px 271px 78px 262px #0000008a; */
            z-index: 1100;
            transform-origin: top right;
            /* transform: translateX(150%); */
            transform: scale(0);
            opacity: 0;
            transition: transform 0.5s ease-in-out,
                opacity 0.5s ease-in-out;
        }

        .navbar .navbar-items-active {


            opacity: 1;
            transform: scale(1);

            /* transform: translateX(0%); */
        }



        .navbar-item {
            
            border-bottom: 0.01px solid #8080802e;
        }

        .navbar-dropdown:after {
            display: none;
        }

        .navbar-dropdown:before {

            content: "";
            position: absolute;
            top: 18px;
            left: -3px;
            /* Example: right:10px; */
            display: inline-block;
            border-right: 4px solid transparent;
            border-top: 4px solid var(--secondary);
            border-left: 4px solid transparent;

        }

        .navbar-btn {
            transform: translateX(-50%);
        }

        .navbar-hamburger {
            display: block;
        }


        .navbar-dropdown-menu{
            transition: none;
        }
        .navbar-item:hover .navbar-dropdown-menu {
         
                position: relative;
                left: -9px;
                width: 100%;
                border-radius: 0;
                opacity: 1;
                transform: scale(1);
                /* transform: translateX(-50%); */
        }

        .bg-cover-active {
           opacity: 1;
        transform:scale(1);

         
            

        }
    }
</style>
<nav class="navbar " id="_n_a_v" >
    <div class="container d-flex justify-content-between align-items-baseline">
        <div class="navbar-brand">
            {%if clubinfo and clubinfo.logo%}
            <a href="{%url 'core:index'%}"><img  src="{{clubinfo.logo.url}}" alt="logo" title="{{clubinfo.sort_name}}" srcset=""></a>
            
            {%else%}

            <img src=""  alt="logo" srcset="">


            {%endif%}
        </div>
        <div class="navbar-items">
            <div class="navbar-item">
                {%  url 'core:index' as home_url %}
                <a href="{{home_url}}" {%if request.get_full_path == home_url%} class="navbar-active" {%endif%}>Home</a>
            </div>
            <!-- <div class="navbar-item">
                {%  url 'core:articles' as article_url %}
                <a href="{{article_url}}" {%if url_active == 'article' or request.get_full_path == article_url%} class="navbar-active" {%endif%}>Article</a>
            </div>
            <div class="navbar-item">
                {%  url 'core:publications' as publications_url %}
                <a href="{{publications_url}}" {%if url_active == 'publication' or request.get_full_path == publications_url%} class="navbar-active" {%endif%}>Publication</a>
            </div> -->
            
            <div class="navbar-item">
                
                <a href="" role="button" class="navbar-dropdown {%if url_active == 'activity'%}
                                                                    navbar-active 
                                                                {%endif%}">Activity</a>
                
                <div class="navbar-dropdown-menu">
                    <a href="{%url 'core:articles'%}" class="dropdown-item"> Articles </a>
                    <a href="{%url 'core:publications'%}" class="dropdown-item"> Publication </a>
                    
                </div>
            </div>


            <div class="navbar-item">
                {%  url 'core:gallery' as gallery_url %}
                <a href="{{gallery_url}}" {%if request.get_full_path == gallery_url%} class="navbar-active" {%endif%}>Gallery</a>
            </div>





            <div class="navbar-item">
                {#url_active context coming form event_list view #}
                <a href="" role="button"  class=" navbar-dropdown {%if url_active == 'event'%}
                                                                      navbar-active 
                                                                    {%endif%}">Events</a>


                <div class="navbar-dropdown-menu">
                    <div class="text-center" style="border-bottom:  0.2px solid var(--text_in_secondary); padding: 4px;">
                        <a href="#" class="" style="color: var(--text_in_secondary); "> Rotary Year </a>

                    </div>

                    {%for semester in semester_list%}
                    <a href="{%url 'core:event_list' slug=semester.slug%}" class="dropdown-item"> {{semester}} </a>
                    {%endfor%}
                </div>

            </div>

            <div class="navbar-item">
                {%  url 'core:news' as url_str %}
                <a href="{{url_str}}" {%if  url_active == "news" or request.get_full_path == url_str%} class="navbar-active" {%endif%}>News</a>
            </div>

            <div class="navbar-item">
                {#url_active context coming form members_list view #}
                <a href="" role="button" class="navbar-dropdown {%if url_active == 'Governing Body'%} navbar-active {%endif%}">Governing Body</a>


                <div class="navbar-dropdown-menu">
                    {%for view in member_views%}
                    <a href="{%url 'members:members_list' slug=view.slug%}" class="dropdown-item"> {{view}} </a>
                    {%endfor%}
                </div>
            </div>

            <div class="navbar-item">
                {%  url 'members:alumni_view' as alumni_view %}

                <a href="{{alumni_view}}"  {%if request.get_full_path == alumni_view%} class="navbar-active" {%endif%} >Alumni</a>
            </div>

            <div class="navbar-item">
                <a href="#">Career</a>
            </div>

        </div>
        <div class="navbar-btn">
            <a href="{%url 'core:signup'%}" title="Register to {{clubinfo.sort_name}}">
                JoinUs
            </a>
        </div>

        <div class="align-self-center navbar-hamburger" onclick="hambargerAnimation()">
            <div class="hamburger-lines">
                <span class="line line1"></span>
                <span class="line line2"></span>
                <span class="line line3"></span>
            </div>
        </div>





    </div>

    <div class="bg-cover" onclick="hambargerAnimation()"></div>

</nav>


<div id="scroll-d"></div>

<script>
    function hambargerAnimation() {

        document.querySelector('.hamburger-lines .line1').classList.toggle('line1-active');
        document.querySelector('.hamburger-lines .line2').classList.toggle('line2-active');
        document.querySelector('.hamburger-lines .line3').classList.toggle('line3-active');

        document.querySelector('.navbar-items').classList.toggle('navbar-items-active');
        document.querySelector('.bg-cover').classList.toggle('bg-cover-active');



    }


    var scroll_d = document.getElementById('scroll-d').offsetTop;
    var nav = document.getElementById('_n_a_v');
    var nav_fix = false;
    window.onscroll = function () {
        // called when the window is scrolled.  

        if (!nav_fix && window.scrollY > scroll_d) {

            nav.classList.add('fixed-top');
            nav_fix = true;
        }
        if (nav_fix && window.scrollY < 1) {
            nav.classList.remove('fixed-top');
            nav_fix = false;
            console.log('rmemove')

        }



    }
</script>

core/templates/reg_complect_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration complect</title>
</head>
<body>


<h5>Dear <i>{{username}}</i>,</h5>
<p>
    Thank you for join us, your registration has complete successfully.
</p>
<pre>
Best regrade,
{{clubname}}
</pre>

</body>
</html>