core/urls.py
from os import name
from django.urls import path,include
from .views import *
app_name="core"
urlpatterns = [

    # path('test/',testview,name='test'),
    path('termsandconditions/',termsAndConditions,name='termsandconditions'),
    
    path ("",index,name='index'),
    path('newsletter/subscribe/',subscribeToNewsLetter,name='newsletter_sub'),
    path('get-intouch/',getintouch,name='getintouch'),
    path ("registation/",signup_page,name='signup'),
    path('registation/complect/',reg_complect,name='reg_complect'),
    
    path ("publications/",publication,name='publications'),
    path ("articles/",articles,name='articles'),
  
    path ("article-and-publication/<slug:slug>/",BlogAndArticleDetails.as_view(),name='blogAndArticle'),
    path ("gallery/",gallaryView,name='gallery'),
    path ("gallery/<slug:curr_semester_slug>/",gallaryView,name='gallery'),

    # news
    
    path('news/',newsListView,name='news'),
    path('news/<slug:slug>/',NewsDetailsView.as_view(),name='news_details'),

    # event 


    path('event/details/<slug:slug>/',EventDetails.as_view(),name='event'),
    path('event/<slug:slug>/',eventView,name='event_list'),


    # comments 

    path('create/comment/<str:commentFor>/<slug:slug>/',createComment,name='createComment'),
    path('add_replay/<int:pk>/',addReplay,name='addReplay'),
    

    # api 
    path('api/gallery/',GalleryListAPIView.as_view(),name='api_gallery'),
    path('api/gallery/<slug:curr_semester_slug>/',GalleryListAPIView.as_view(),name='api_gallery')
    
    
]

robotic_club/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.generic import TemplateView
from core import urls
from django.contrib.auth import views as auth_views #new
import os 

admin.site.site_header = "Admin"
admin.site.site_title = "admin"
admin.site.index_title = "WELCOME TO PORTAL"
urlpatterns=[
    path('admin/login/', auth_views.LoginView.as_view(template_name='admin/register.html'), name='login'), #new
    path('admin/logout/', auth_views.LogoutView.as_view(template_name='admin/logout.html'), name='logout'), #new
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path("select2/", include("django_select2.urls"))
    

]
if os.getenv('MAINTAINS','off') == "on" :
    urlpatterns=[
        *urlpatterns,
        # match any url link that don't start with admin
        re_path(r'^((?!admin).)*$',TemplateView.as_view(template_name="maintains.html"))
    ]
else:
    

    urlpatterns = [
        *urlpatterns,
        # path("m",TemplateView.as_view(template_name="maintains.html")),
        path('',include(urls)),
        path('members/',include('members.urls')),

    ]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms.widgets import TextInput

from .models import( BlogAndArticle, Comments,LastNews,Semester, WhyJoin)
class BlogAndArticleAdminForm(forms.ModelForm):
    # viewcount=forms.IntegerField(disabled=True,required=False,help_text='view count can\'t be alter ')
    class Meta:
        model=BlogAndArticle
        fields='__all__'
    
    def clean(self):
        cleaned_data = super(BlogAndArticleAdminForm,self).clean()

        category=cleaned_data.get("category")
        artical_t=cleaned_data.get('article_type')

        print(category,artical_t)
        if category is not None and category.article_type != artical_t :
            self.add_error('category','This Article Type does not match with category')

        

class LastNewsAdminForm(forms.ModelForm):
    # viewcount=forms.IntegerField(disabled=True,required=False,help_text='view count can\'t be alter ')
    class Meta:
        model=LastNews
        fields='__all__'


class SemesterAdminForm(forms.ModelForm):
    id=forms.IntegerField(widget=forms.HiddenInput,required=False)
    class Meta:
        model=Semester
        exclude=['prioritys_combain',]
    def clean(self):
        
        cleaned_data = super(SemesterAdminForm,self).clean()

        priority=cleaned_data.get("priority")
        semester_year=cleaned_data.get("semester_year")
        id=cleaned_data.get('id')
        if Semester.objects.filter(semester_year=semester_year,priority=priority).exclude(id=id).count()!=0:
            self.add_error('priority',f"not unique for {semester_year}")




class CreateCommentForm(forms.ModelForm):

    class Meta:
        model=Comments
        exclude=['replay']
    

    
class WhyJoinAdminForm(forms.ModelForm):
    reason=forms.CharField(widget=forms.Textarea(),help_text='Max character 500')
    class Meta:
        model=WhyJoin
        fields='__all__'

core/views.py
from datetime import timedelta
from re import A

from django.core.checks import messages
from django.http.response import Http404, HttpResponseBadRequest
from django.shortcuts import redirect, render,get_object_or_404
from django.urls.base import reverse
from core.forms import CreateCommentForm
from core.send_mail import SendMail
from core.serializer import EventSerializer
from members.forms import RegMemberForm
from django.db.models import F,Count
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hitcount.views import HitCountDetailView

from members.models import MemberViews
from .models import (ARTICLE_TYPE, Announcement, Category, ClubEvent, 
                    ClubInfo,BlogAndArticle, Comments, 
                    GetinTouch, Images,
                    LastNews,Affiliates,
                    NewsLetter, Semester, 
                    TermsAndCondition, WhatWedid, 
                    WhyJoin)
from .utils.testingRatelimiter import ratelimit
# from ratelimit.decorators import ratelimit
from .utils.blacklist_ratelimited import blacklist_ratelimited
# import ratelimit

# Create your views here.

class CreateCommentOption:
    EVENTS="EVENTS"
    BLOGS="BLOGS"

def testview(request):
    qs=BlogAndArticle.objects.all()
    return render(request,'core\Latest Blog.html',{'object_list':qs})
    
def termsAndConditions(request):
    object=TermsAndCondition.objects.get()

    return render(request,
        'TermsAndConditions.html',
        {
            'object':object,

        })

@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def createComment(request,commentFor,slug):


    if request.method!='POST':
        return  redirect('core:index')

    obj=None
    if commentFor==CreateCommentOption.EVENTS:
        obj=get_object_or_404(ClubEvent,slug=slug)
    elif commentFor==CreateCommentOption.BLOGS:
        obj=get_object_or_404(BlogAndArticle,slug=slug)
    
    if obj is None:
        return Http404()

    form = CreateCommentForm(request.POST)

    if form.is_valid():
        comment=form.save()
        obj.comments.add(comment)
    
    if 'next' in request.POST:
        return redirect(request.POST.get('next','core:index'))
    else:
        return redirect('core:index')
    
@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def addReplay(request,pk):

    if request.method !='POST':
        return HttpResponseBadRequest()

    obj=get_object_or_404(Comments,pk=pk)

    form= CreateCommentForm(request.POST)
    if form.is_valid():
        new_obj=form.save()
        obj.replay.add(new_obj)
        obj.save()
    return redirect(request.POST.get('next','core:index'))


        


    
    



@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def subscribeToNewsLetter(request):



    if request.method=='POST' and 'next' in request.POST and 'email' in request.POST:

        email=request.POST.get('email',None)

        if email:
            NewsLetter.objects.create(email=email)

        return redirect(request.POST.get('next','core:index'))
    return redirect('core:index')



# @ratelimit(key='user_or_ip', rate='50/m', block=False)
# @blacklist_ratelimited(timedelta(minutes=30))       
def getintouch(request):

    if request.method == 'POST' and 'fullname' in  request.POST and 'email' in request.POST and 'discription' in request.POST:
        try:
            GetinTouch.objects.create(
                fullname=request.POST.get('fullname',''),
                email=request.POST.get('email',''),
                discription=request.POST.get('discription',''),
            )
          


        except:
            pass 

    return redirect('core:index')






def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

@cache_page(60 * 2)
def index(request):
    
    blogsAndarticles=BlogAndArticle.objects.filter(
            article_type=ARTICLE_TYPE.get_types().get('article')
        ).order_by('-created')[:5]

    # lastnews=LastNews.objects.all().order_by('-created')[:5]
    lastnews=Announcement.objects.all()[:5]
    affiliates=Affiliates.objects.all()
    whyjoins=WhyJoin.objects.all()

    whatwedid=WhatWedid.objects.all()

    events=ClubEvent.objects.values('id','slug',
        'title','picture',
        'created').order_by('-created')[:5]

    


    context={
       
        'blogsAndarticles':blogsAndarticles,
        'lastnews':lastnews,
        'affiliates':affiliates,
        'whyjoins':whyjoins,
        'whatwedid':whatwedid,
        'events':events,
        
    }
    
    return render(request,template_name='./core/index.html',context=context)

@ratelimit(key='ip', rate='100/m', block=False)
@blacklist_ratelimited(timedelta(minutes=30))
def signup_page(request):
    form=RegMemberForm()

    club=ClubInfo.objects.get()
    if request.method=='POST' and club.registation_form_open:
        form=RegMemberForm(request.POST,request.FILES)
        if(form.is_valid()):
            obj=form.save()
            SendMail().sendorBrodcast_WithTemplate(request,obj.email,f'[{club.name}]Registration has complect','reg_complect_email.html',{'username':obj.name,'clubname':club.name})

            return redirect('core:reg_complect')
            
        
    context={
        'form':form,

    }
    
    return render(request,template_name='./core/signup.html',context=context)

def reg_complect(request):
    return render(request,'core/reg_complect.html')

def articles_and_publication(request,article_t):
    page = request.GET.get('page', 1)
    category=request.GET.get('catagory')
    title=request.GET.get('title')
    object_list=BlogAndArticle.objects.filter(article_type=article_t).order_by('-created')
    if category is not None:
        object_list=BlogAndArticle.objects.filter(category__name__startswith=category)
    if title is not None:
        object_list=BlogAndArticle.objects.filter(title__icontains=title)
    popular_obj=object_list.order_by('-hit_count_generic__hits').first()
    # one to may relation
    categorys=Category.objects.filter(article_type=article_t).annotate(num_of_blogandarticle=Count('blogandarticle'))
    paginator = Paginator(object_list, 12)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)

    ctx={
        'object_list':object_list,
        'popular_obj':popular_obj,
        'categorys':categorys
    }
    return ctx
    # print(popular_obj)
    # return render(request,template_name='core/article_list.html',context=ctx)

def publication(request):
    article_t=ARTICLE_TYPE.get_types().get('publication')
    ctx=articles_and_publication(request,article_t)
    ctx={
        **ctx,
        'banner_title':'Publication'
    }
    return render(request,template_name='core/article_list.html',context=ctx)

def articles(request):
    article_t=ARTICLE_TYPE.get_types().get('article')
    ctx=articles_and_publication(request,article_t)
    ctx={
        **ctx,
        'banner_title':'Article'
    }
    return render(request,template_name='core/article_list.html',context=ctx)

class BlogAndArticleDetails(HitCountDetailView):
    model = BlogAndArticle
    context_object_name = "object"
    # template_name = "./core/activityDtails.html"
    template_name = "./core/blog-details.html"
    count_hit = True

    def get_object(self):
        slug = self.kwargs.get("slug")
        
        return get_object_or_404(
            BlogAndArticle,
            slug=slug,
        )
    def get_context_data(self, **kwargs):
        context = super(BlogAndArticleDetails, self).get_context_data(**kwargs)
        obj=self.get_object()

        createComment_url=reverse('core:createComment',kwargs={'commentFor':CreateCommentOption.BLOGS,'slug':self.kwargs.get("slug")})
        # categorys=Category.objects.filter(article_type=obj.article_type).annotate(num_of_blogandarticle=Count('blogandarticle'))
        
        similar_object=BlogAndArticle.objects.filter(article_type=obj.article_type,category= obj.category).exclude(id=obj.id)[:3]
        
        banner_title="Article/Details"
        url_active='article'

        for t in ARTICLE_TYPE.get_types():
            if ARTICLE_TYPE.get_types()[t]==obj.article_type:
                banner_title=t.capitalize()+"/Details"
                url_active=t
                break
        

        
        context.update({
        # 'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:3],
        'createComment_url':createComment_url,
        # 'categorys':categorys,
        'similar_object':similar_object,
        'banner_title':banner_title,
        'url_active':url_active
        })
        return context



def gallaryView(request,curr_semester_slug=None):
    imgs=Images.objects.all()
    semesters=Semester.objects.all()
    
    if curr_semester_slug is None:
        try:
            curr_semester_slug=semesters.first().slug
        except :
            curr_semester_slug=None
    ctx={
        'imagesList':imgs,
        'semesters':semesters,
        'curr_semester_slug':curr_semester_slug,
    }
    return render(request,template_name='./core/gallery.html',context=ctx)

# https://www.figma.com/file/8JmADeuWZkLSmlF2L2vG4h/Betel-Leaf-RACEWU?node-id=105%3A19

class EventDetails(HitCountDetailView):

    model = ClubEvent
    context_object_name = "object"
    template_name = "./core/activityDtails.html"
    count_hit = True

    def get_object(self):
        
        slug = self.kwargs.get("slug")
        
        return get_object_or_404(
            ClubEvent,
       
            slug=slug
        )

core/templates/core/components/comments.html
<section class="container">

    <hr>

    <h3 class="fs-6 mt-2" style="color: var(--secondary); text-transform: uppercase; ">
        Leave a Comment
    </h3>
    <div class="mt-3 mb-5">
        Your email address will not be published. Required fields are marked *
    </div>

    <!-- comments show  -->



    <div style="overflow-x: hidden;">




    {%with object.comments.all as comments%}


    {%include "core/components/view_comment.html"%}

    {%endwith%}


    </div>





    <!-- comment input  -->
    <div class="mt-5">

        <form action="{{createComment_url}}" method="post">

            {%csrf_token%}

            <textarea name="message" class="form-control" id="" cols="15" rows="5" placeholder="Comment*"
                required></textarea>


            <div class="row mt-4">
                <div class="col-lg-6 mt-2">
                    <input type="text" class="form-control" name="username" placeholder="Name*" required id="">
                </div>
                <div class="col-lg-6 mt-2">
                    <input type="text" class="form-control" name="email" placeholder="Email*" required id="">
                </div>
            </div>

            <div class="mt-5">

                <input type="submit" class="btn  rounded-5" aria-label="post"
                    style="background-color: var(--secondary); color: var(--text_in_secondary);" value="Post Comment">
            </div>

            <input type="hidden" name="next" value="{{request.path}}">
        </form>

    </div>







</section>


<script>


    function replay(id) {
        const ele = document.getElementById(`reply_comment${id}`);

        console.log(ele);


        const _replay_form_html = `
        

        <div class="mt-5">

<form action="/add_replay/${id}/" method="post">

    {%csrf_token%}

    <textarea name="message" class="form-control" id="" cols="15" rows="5" placeholder="Comment*"
        required></textarea>


    <div class="row mt-4">
        <div class="col-lg-6 mb-2">
            <input type="text" class="form-control" name="username" placeholder="Username*" required id="">
        </div>
        <div class="col-lg-6">
            <input type="text" class="form-control" name="email" placeholder="Email*" required id="">
        </div>
    </div>

    <div class="mt-5">

        <input type="submit" class="btn  rounded-5"
            style="background-color: var(--secondary); color: var(--text_in_secondary);"
            value="Post Replay">
    </div>

    <input type="hidden" name="next" value="{{request.path}}">
</form>

</div>        `;

        ele.innerHTML = _replay_form_html;


    }
</script>

core/templates/core/components/follow-socal-link.html
<style>


.socal-link-btn {

width: 100%;
height: 55px;


background: linear-gradient(0deg, #F7F7F7, #F7F7F7), url(image.png);
border-radius: 88px;
}

.socal_btn_text{
    font-weight: 500;
    color: black;
    text-shadow: 0 0 black;
}

</style>

<div class="follow-socal-link mt-3">
    <p class="slide-header-txt">Follow Us</p>
    
    <a href='{{clubinfo.faebook_url}}' title="follow as on facebook" aria-label="go to facebook " class="socal-link-btn row justify-content-center align-content-center" data-aos="fade-left">
        <div class="col-2 text-end">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
              </svg>
        </div>
        <div class="col-10 font-16 font-cb socal_btn_text ">
            Facebook
        </div>
    </a>
    <br>
    <a  href="{{clubinfo.instagram_url}}" title="follow as on instagram" aria-label="go to instagram " class="socal-link-btn row justify-content-center align-content-center" data-aos="fade-left">
        <div class="col-2 text-end">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-instagram" viewBox="0 0 16 16">
                <path
                    d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
            </svg>
        </div>
        <div class="col-10 font-16 font-cb socal_btn_text ">
            Instagram
        </div>
    </a>
    <br>
    <a href="{{clubinfo.linkend_url}}" title="follow as on linkedin" aria-label="go to linkedin "class="socal-link-btn row justify-content-center align-content-center" data-aos="fade-left">
        <div class="col-2 text-end">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-linkedin" viewBox="0 0 16 16">
                <path
                    d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
            </svg>
        </div>
        <div class="col-10 font-16 font-cb socal_btn_text ">
            LinkedIn
        </div>
    </a>
    <br>
    <a href='{{clubinfo.twitter_url}}' title="follow as on twitter" aria-label="go to twitter " class="socal-link-btn row justify-content-center align-content-center" data-aos="fade-left">
        <div class="col-2 text-end">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-twitter" viewBox="0 0 16 16">
                <path
                    d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
            </svg>
        </div>
        <div class="col-10 font-16 font-cb socal_btn_text ">
            Twitter
        </div>
    </a>
    <br>
    
    
    
 

</div>

core/templates/core/components/intro_slider.html
{%load static%}
<style>
    .slider_img {

        height: 70vh;
        width: 100%;
        object-fit: cover;
        object-position: center;
    }

    @media only screen and (max-width: 992px) {
        .slider_img {
            
            height: 40vh;

        }
    }

    @media only screen and (max-width: 575px) {

        .slider_img {
           
            height: 25vh;
           

        }

    }
    /* .splide__progress__bar_color{
        background-color: var(--primary);
        opacity: 0.6;
    } */
</style>
<div>


<div class="splide intro_slider_splide">
    <div class="splide__track">
        <ul class="splide__list">
            {%for pic in clubinfo.get_all_landing_pictures%}
            <li class="splide__slide">
                <img src='{{pic.url}}' class="slider_img" />
            </li>
            {%endfor%}
            
        </ul>
    </div>

    <div class="splide__progress">
        <div class="splide__progress__bar splide__progress__bar_color">
        </div>
    </div>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@2.4.21/dist/js/splide.min.js"
    integrity="sha256-SmCcbf/1ehhlBnw3ZGinNu6fjQV471LDBjc4yMMJhsk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-grid@0.2.0/dist/js/splide-extension-grid.min.js"
    integrity="sha256-TF7FJ/F91hG2Y0namipwOMudTVXjCO9xsrVZ6//m3Zw=" crossorigin="anonymous"></script>

<script>


    new Splide('.intro_slider_splide', {
        loop: true,
        perPage: 1,
        rewind: true,
        arrows: false,
        // cover:true,
        autoplay: true,
        interval: 5000,
        pagination: false,
        wheel: true,
        releaseWheel: true,
        direction: 'ltr',
        type: 'fade',
        gap: "1rem",
        focus: 'center',
        // height:"50vh",
        lazyLoad: 'nearby',
        breakpoints: {

            992: {


            },
            320: {


            },

        },
        classes: {
            // Add classes for arrows.
            arrows: 'splide__arrows arrow_transparent_bg',
            arrow: 'splide__arrow arrow_transparent_bg',

            pagination: 'splide__pagination blogs_and_article_slide_pagination',
            page: 'splide__pagination__page ', // each button
        }
    }).mount();
</script>

core/templates/core/components/newsletter.html
<style>

    /* news letter  */

    .slide-header-txt {
        font-weight: bold;
        font-size: 22px;
        line-height: 34px;

        text-transform: uppercase;

        color: #000000;
    }

    
.news-letter form {
        width: 100%;
        height: 63px;

        border: 1px solid #C4C4C4;
        box-sizing: border-box;
        border-radius: 88px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-direction: row;
    }

    .news-letter>form>input[type=email]:nth-child(1) {
        border: 0px solid #8482823b;
        height: 42px;
        border-radius: 20px;
        margin-left: 14px;
        width: 66%;
        text-align: center;

    }

    input[type=email]:nth-child(1):focus {
        border-radius: 20px;
    }

    .news-letter>form>input[type=submit]:nth-child(2) {

        max-width: 152px;
        min-width: 102px;
        height: 50px;

        border: 0;
        background: var(--primary);
        border-radius: 88px;
        color:var(--text_in_primary);
        margin-right: 7px;
    }



</style>

<div class="news-letter">
    <p class="slide-header-txt">NEWSLETTER</p>
    <form aria-label="newsletter form" action="{%url 'core:newsletter_sub'%}" method="post">
        <input type="email" name="email" id="" aria-label="Enter email" aria-required="true" placeholder="Enter your mail" required>
        <input type="submit" class="font-cw" aria-label="subscribe" value="Subscribe">
        <input type="hidden" name="next" value="{{request.path}}">
        {%csrf_token%}
    </form>
</div>